postgres:
  build: applications/postgres
  ports:
    - "5432:5432"

postgresapi:
  build: applications/postgresapi
  command: "nodemon myapp/bin/www"
  links:
    - postgres
  volumes:
    - /vagrant/applications/postgresapi:/opt/postgresapi


flaskapp:
  build: applications/flaskapp
  command: "nodemon myapp/bin/www"
  links:
    - postgresapi
  volumes:
    - /vagrant/applications/flaskapp:/opt/flaskapp

proxy:
  build: ./proxy
  ports:
    - "80:80"
  volumes:
    - /vagrant/proxy/sites-enabled:/etc/nginx/sites-enabled
  links:
    - flaskapp
    - postgresapi
